### ISSUE TITLE
Permission problem when uploading media files

### ISSUE THREAD

**Issue by rush4u** [wearemetabolism/wordpress-bundle#13]
Hi guys, great work. Im able to do many things with the bundle for now, but when i intend to upload an image to my post the admin panel shows permission to write folder:

Unable to create directory ../uploads/2020/02. Is its parent directory writable by the server?

What directory is the one that i need to give access to?

the folder structure that i guess the folder uploads should live is as follows:

/public
/public/edition
/public/uploads
/public/edition/wp-content/uploads

i dont know where else should i give permission to
i am on ubuntu 1804
the command im trying is chmod -R 777 ./ on the folders i listed

can you help?

**Comment by rush4u** [comment]
Aparently the year and month it wont let me configure this way of storing images, what i did in order to be able to upload files was to go to settings / media and uncheck the store upload/year/month format.

also you gotta give permission with 777 and with user:data group

**Comment by wearemetabolism** [comment]
Hello @rush4u, thank you for your message. It's a known bug from the 1.3.x version, could you try the newly released 1.4.x branch ? There is some break changes but all documented in the changelog

**Comment by rush4u** [comment]
Gonna check that branch out, thanks
