### ISSUE TITLE
Set root domain url to wp homepage

### ISSUE THREAD

**Issue by FranckPiazza** [wearemetabolism/wordpress-bundle#16]
I do not find the way to load the front page on the root domain (ex : https.//www.mydomain.com)
Instead I have a 404 page
![image](https://user-images.githubusercontent.com/1138310/123427697-3dfa0080-d5c5-11eb-841e-b6becaaabe6a.png)

When the wp reading setting are set on Your latest posts, the post load properly.

Best Regards

**Comment by jerome-barbato** [comment]
Hello @FranckPiazza which version are you using ? Could you try the 1.5.x ? The documentation is better also you have a demo here : https://github.com/wearemetabolism/wordpress-bundle-demo

**Comment by FranckPiazza** [comment]
Hi, I have clone the demo repo, can you tell me where is the documentation ? In the vendor ?

**Comment by FranckPiazza** [comment]
> Hello @FranckPiazza which version are you using ? Could you try the 1.5.x ? The documentation is better also you have a demo here : https://github.com/wearemetabolism/wordpress-bundle-demo
