### ISSUE TITLE
Gutenberg Question 

### ISSUE THREAD

**Issue by FranckPiazza** [wearemetabolism/wordpress-bundle#18]
wp feature img not in gutenberg right column but there in classic editor?.

My misstake or not ?

regard

**Comment by jerome-barbato** [comment]
Hi @FranckPiazza I'm not familiar with Gutenberg but normally the bundle doesn't interfere with WordPress admin functionality, but I will take a look asap

**Comment by FranckPiazza** [comment]
I have another twig render pb withe the $context post,

I have add social block in éditor : 

The render in the source look like this : 
<img width="536" alt="Capture d’écran 2021-08-05 à 11 43 47" src="https://user-images.githubusercontent.com/1138310/128329597-1a10dc1b-6fbd-4251-b601-d546a418ddef.png">

I have add in app.js 

- require('../../public/edition/wp-includes/css/dist/block-library/style.css');
- require('../../public/edition/wp-includes/js/dist/i18n.min.js');
- require('../../public/edition/wp-includes/js/dist/block-library.min.js');

But its still not working, when in `dd(the_content());` in the page controler the source is ok but not with the context in the twig.

I have something to do ?

Regards

**Comment by jerome-barbato** [comment]
Hi @FranckPiazza I have pushed a fix for that, could you tell me if it's ok for you now ?
In fact post.content was not filtered using `apply_filters( 'the_content', $content );` that was the issue
