### ISSUE TITLE
 "Error: Cannot declare class Metabolism.." When i try to load frontend 

### ISSUE THREAD

**Issue by umaneyes** [wearemetabolism/wordpress-bundle#19]
I can access to the Backend 

When i try to load frontend 
https://127.0.0.1:8000/edition/myroute
I got this error : 
**Error: Cannot declare class Metabolism\WordpressBundle\Permastruct, because the name is already in use**

How to solve it please ?

Symfony 5.2
PHP FPM 7.3.28 
mysql:5.7.34

**Comment by jerome-barbato** [comment]
Hi there, the front url might be https://127.0.0.1:8000/myroute, do you still have an issue ?

**Comment by umaneyes** [comment]
> Hi there, the front url might be https://127.0.0.1:8000/myroute, do you still have an issue ?


I work now with demo bubdle 
You can close issue
 thanks

**Comment by celtic34fr** [comment]
Retour sur mes expérimentations et développement :
-> on peut mettre en place un thème WordPress (Enfold pour mon cas) moyennant de réaliser quelques templates pour reprendre la structure du code Php du thème WordPress, et en faisant quelques liens d'appel des méthodes du thème installé au travers d'une extension spécifique à Twig.
-> afin de disposer des données de base pour avoir les paramètres du thème WordPress installé, j'ai étendu le service Context au niveau du Trait pour : 
1/ ajouter une accès via PDO à la base de données WordPress
2/ en intégrant les paramètres du thème WordPress stockés dans la table wp_options
-> pour certaines pages, j'ai repris le formalisme des menus en sortie pour avoir les mêmes présentation avec succès

Même si cela implique de la programmation niveau Trait, template et services, il est possible alors d'utiliser WordPress normalement et intégrant des pages métiers sans trop de soucis, hors ceux de communication avec le client ou les personnes ayant à définir le process que WordPress ne peut facilement satisfaire.

Je reste à votre disposition si vous désirez plus d'information et de retour d'expérience de ma part.

Celtic34fr
