### ISSUE TITLE
Logo, title, slogan: escaped chain that must not be

### ISSUE THREAD

**Issue by celtic34fr** [wearemetabolism/wordpress-bundle#21]
When I try to add a logo to the identity of Website, I have that :
````
<div class="site-logo">
    &lt;span class="custom-logo-link"&gt;&lt;img width="175" height="175" src="/uploads/2021/08/cropped-picto-rse.png" class="custom-logo" alt="" /&gt;&lt;/span&gt;
</div>
````

And when my slogan is : "c'est un test", the page return` "c&#039;est un test"`
All the string were escaped, when a raw string where needed.

to remove this bug you must add to the restitution of fields or function '| raw' in the source file templates / template-parts / header / site-branding.html.twig on lines 12, 17, 19, 25, 33 and 44 (logo, tiltle of site, slogan of site, mai_menu items et social_menu items).

Celtic34fr
Béziers - France

**Comment by jerome-barbato** [comment]
Thank you you are right. I have updated the demo.
