### ISSUE TITLE
impossible d'installer metabolism/wordpress-bundle - can't install metabolism/wordpress-bundle

### ISSUE THREAD

**Issue by celtic34fr** [wearemetabolism/wordpress-bundle#28]
quand je tente d'installer metabolism/wordpress-bundle, j'ai le retour suivant : 

`composer require metabolism/wordpress-bundle
Using version ^1.4 for metabolism/wordpress-bundle
./composer.json has been updated
Running composer update metabolism/wordpress-bundle
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - metabolism/wordpress-bundle[1.4.4, ..., 1.4.12] require metabolism/wordpress-core-installer 1.0.* -> satisfiable by metabolism/wordpress-core-installer[1.0.0].
    - metabolism/wordpress-bundle[1.4.13, ..., 1.4.15] require metabolism/package-actions 1.2.* -> satisfiable by metabolism/package-actions[1.2.0, 1.2.1, 1.2.2, 1.2.3].
    - metabolism/wordpress-bundle[1.4.0, ..., 1.4.3] require ext-posix * -> it is missing from your system. Install or enable PHP's posix extension.
    - metabolism/wordpress-core-installer 1.0.0 requires composer-plugin-api ^1.0 -> found composer-plugin-api[2.2.0] but it does not match the constraint.
    - metabolism/package-actions[1.2.0, ..., 1.2.3] require symfony/filesystem ^3.0|^4.0|^5.0 -> found symfony/filesystem[v3.0.0, ..., v3.4.47, v4.0.0, ..., v4.4.37, v5.0.0, ..., v5.4.3] but the package is fixed to v6.0.3 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - Root composer.json requires metabolism/wordpress-bundle ^1.4 -> satisfiable by metabolism/wordpress-bundle[1.4.0, ..., 1.4.15].

To enable extensions, verify that they are enabled in your .ini files:
    - H:\wamp64\bin\php\php8.0.13\php.ini
You can also run `php --ini` in a terminal to see which files are used by PHP in CLI mode.
Alternatively, you can run Composer with `--ignore-platform-req=ext-posix` to temporarily ignore these required extensions.

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
You can also try re-running composer require with an explicit version constraint, e.g. "composer require metabolism/wordpress-bundle:*" to figure out if any version is installable, or "composer require metabolism/wordpress-bundle:^2.1" if you know which you need.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.`

=> je suis Sous >Windows 10 - composer 2.2.6 - WampServer 3.2.7 - PHP/8.0.13

Après recherche, ext-posix ou toute extension posix pour Php n'existe pas pour Windows .... que faire alors ?

-----------------------------------

When I try to install metabolism/wordpress-bundle, I get the following return:

`composer require metabolism/wordpress-bundle
Using version ^1.4 for metabolism/wordpress-bundle
./composer.json has been updated
Running composer update metabolism/wordpress-bundle
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - metabolism/wordpress-bundle[1.4.4, ..., 1.4.12] require metabolism/wordpress-core-installer 1.0.* -> satisfiable by metabolism/wordpress-core-installer[1.0.0].
    - metabolism/wordpress-bundle[1.4.13, ..., 1.4.15] require metabolism/package-actions 1.2.* -> satisfiable by metabolism/package-actions[1.2.0, 1.2.1, 1.2.2, 1.2.3].
    - metabolism/wordpress-bundle[1.4.0, ..., 1.4.3] require ext-posix * -> it is missing from your system. Install or enable PHP's posix extension.
    - metabolism/wordpress-core-installer 1.0.0 requires composer-plugin-api ^1.0 -> found composer-plugin-api[2.2.0] but it does not match the constraint.
    - metabolism/package-actions[1.2.0, ..., 1.2.3] require symfony/filesystem ^3.0|^4.0|^5.0 -> found symfony/filesystem[v3.0.0, ..., v3.4.47, v4.0.0, ..., v4.4.37, v5.0.0, ..., v5.4.3] but the package is fixed to v6.0.3 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - Root composer.json requires metabolism/wordpress-bundle ^1.4 -> satisfiable by metabolism/wordpress-bundle[1.4.0, ..., 1.4.15].

To enable extensions, verify that they are enabled in your .ini files:
    - H:\wamp64\bin\php\php8.0.13\php.ini
You can also run `php --ini` in a terminal to see which files are used by PHP in CLI mode.
Alternatively, you can run Composer with `--ignore-platform-req=ext-posix` to temporarily ignore these required extensions.

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
You can also try re-running composer require with an explicit version constraint, e.g. "composer require metabolism/wordpress-bundle:*" to figure out if any version is installable, or "composer require metabolism/wordpress-bundle:^2.1" if you know which you need.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.`

=> I am under Windows 10 - composer 2.2.6 - WampServer 3.2.7 - PHP/8.0.13

After searching, ext-posix or any posix extension for Php does not exist for Windows....what to do then?

Gilbert ARMENGAUD
Celtic34fr
Béziers - Occitanie - France

**Comment by jerome-barbato** [comment]
Hello @celtic34fr It should be fixed in the upcoming 2.0, could you try it ? https://github.com/wearemetabolism/wordpress-bundle/tree/2.0.x

**Comment by celtic34fr** [comment]
I'll try to install 2.0.x dev version with : 

composer require metabolism/wordpress-bundle ^2.0.x

after installating all packages it's return :  

`Executing script cache:clear [KO]
 [KO]
Script cache:clear returned with error code 255
!!
!!  Fatal error: During class fetch: Uncaught ReflectionException: Class "Metabolism\WordpressBundle\Traits\ContextTrait" not found while loading "App\Service\Context". in H:\wamp64\www\wordpress-bundle\vendor\symfony\error-handler\DebugClassLoader.php:284 .....`

I' don't find  Class "Metabolism\WordpressBundle\Traits\ContextTrait" as in the previousd Version ????

**Comment by celtic34fr** [comment]
after add manualy Class Metabolism\WordpressBundle\Traits\ContextTrait, i try to execute : 

`symfony console cache:clear`

it's return : 
` // Clearing the cache for the dev environment with debug true


In routing.php line 38:

  Call to a member function get() on null


cache:clear [--no-warmup] [--no-optional-warmers]`

????

and when i try to access to web site : 

`[ErrorException](http://wordpress-bundle/#trace-box-1)
HTTP 500 Internal Server Error
User Warning: $request must be renamed in "H:\wamp64\www\wordpress-bundle/public/index.php" : $httpRequest = Request::createFromGlobals(); ....`

**Comment by celtic34fr** [comment]
last remark : the administration area is accessible , but i've yhje same error when i want save ou public a page : 
`La mise à jour a échoué. La réponse n’est pas une réponse JSON valide.`

I've the error on article creation too, but on page 'PAges' and 'Articles', in tht e top i've this message : 
There is no controller defined : [Create one](http://wordpress-bundle/edition/wp-admin/edit.php?fix=controller)'

when i click on the link : 
'<html><body>
<br>
<font size="1">

( ! )  Warning:  copy(H:\wamp64\www\wordpress-bundle\vendor\metabolism\wordpress-bundle\src\Plugin/../../samples/controller/BlogController.php):  Failed to open stream: No such file or directory in  H:\wamp64\www\wordpress-bundle\vendor\metabolism\wordpress-bundle\src\Plugin\NoticePlugin.php  on line 36
--


1 | 0.0003 | 367496 | {main}(  ) | ...\edit.php:0
2 | 0.3108 | 10076648 | require_once( 'H:\wamp64\www\wordpress-bundle\public\edition\wp-admin\admin-header.php ) | ...\edit.php:397
3 | 0.3364 | 10182312 | do_action( $hook_name = 'admin_notices' ) | ...\admin-header.php:303
4 | 0.3364 | 10182688 | WP_Hook->do_action( $args = [0 => ''] ) | ...\plugin.php:474
5 | 0.3364 | 10182688 | WP_Hook->apply_filters( $value = '', $args = [0 => ''] ) | ...\class-wp-hook.php:331
6 | 0.3368 | 10183848 | Metabolism\WordpressBundle\Plugin\NoticePlugin->adminNotices( '' ) | ...\class-wp-hook.php:307
7 | 0.3370 | 10184040 | copy( $from = 'H:\\wamp64\\www\\wordpress-bundle\\vendor\\metabolism\\wordpress-bundle\\src\\Plugin/../../samples/controller/BlogController.php', $to = 'H:\\wamp64\\www\\wordpress-bundle/src/Controller/BlogController.php' ) | ...\NoticePlugin.php:36


			<div class="tablenav bottom">

				<div class="alignleft actions bulkactions">
			<label for="bulk-action-selector-bottom" class="screen-reader-text">Sélectionnez l’action groupée</label></div></div>
<div id="wpbody" role="main"><div id="wpbody-content"><div class="wrap"><form id="posts-filter" method="get"><div class="tablenav bottom">
					<div class="alignleft actions">
				</div>
		<div class="tablenav-pages one-page"><span class="displaying-num">1 élément</span>
</div>
		<br class="clear">
	</div>
		
</form>


		<form method="get">
		
		</form>
		
<div id="ajax-response"></div>
<div class="clear"></div>
</div>


<div class="clear"></div></div>
<div class="clear"></div></div>
<div class="clear"></div>
</body>
</html>( ! ) Warning: [copy](http://www.php.net/function.copy)(H:\wamp64\www\wordpress-bundle\vendor\metabolism\wordpress-bundle\src\Plugin/../../samples/controller/BlogController.php): Failed to open stream: No such file or directory in H:\wamp64\www\wordpress-bundle\vendor\metabolism\wordpress-bundle\src\Plugin\NoticePlugin.php on line 36
Call Stack
#	Time	Memory	Function	Location
1	0.0003	367496	{main}( )	...\edit.php:0
2	0.3108	10076648	require_once( 'H:\wamp64\www\wordpress-bundle\public\edition\wp-admin\admin-header.php )	...\edit.php:397
3	0.3364	10182312	do_action( $hook_name = 'admin_notices' )	...\admin-header.php:303
4	0.3364	10182688	WP_Hook->do_action( $args = [0 => ''] )	...\plugin.php:474
5	0.3364	10182688	WP_Hook->apply_filters( $value = '', $args = [0 => ''] )	...\class-wp-hook.php:331
6	0.3368	10183848	Metabolism\WordpressBundle\Plugin\NoticePlugin->adminNotices( '' )	...\class-wp-hook.php:307
7	0.3370	10184040	[copy](http://www.php.net/function.copy)( $from = 'H:\\wamp64\\www\\wordpress-bundle\\vendor\\metabolism\\wordpress-bundle\\src\\Plugin/../../samples/controller/BlogController.php', $to = 'H:\\wamp64\\www\\wordpress-bundle/src/Controller/BlogController.php' )	...\NoticePlugin.php:36

( ! ) Warning: copy(H:\wamp64\www\wordpress-bundle\vendor\metabolism\wordpress-bundle\src\Plugin/../../samples/template/generic.html.twig): Failed to open stream: No such file or directory in H:\wamp64\www\wordpress-bundle\vendor\metabolism\wordpress-bundle\src\Plugin\NoticePlugin.php on line 37
Call Stack
#	Time	Memory	Function	Location
1	0.0003	367496	{main}( )	...\edit.php:0
2	0.3108	10076648	require_once( 'H:\wamp64\www\wordpress-bundle\public\edition\wp-admin\admin-header.php )	...\edit.php:397
3	0.3364	10182312	do_action( $hook_name = 'admin_notices' )	...\admin-header.php:303
4	0.3364	10182688	WP_Hook->do_action( $args = [0 => ''] )	...\plugin.php:474
5	0.3364	10182688	WP_Hook->apply_filters( $value = '', $args = [0 => ''] )	...\class-wp-hook.php:331
6	0.3368	10183848	Metabolism\WordpressBundle\Plugin\NoticePlugin->adminNotices( '' )	...\class-wp-hook.php:307
7	0.3395	10186408	copy( $from = 'H:\\wamp64\\www\\wordpress-bundle\\vendor\\metabolism\\wordpress-bundle\\src\\Plugin/../../samples/template/generic.html.twig', $to = 'H:\\wamp64\\www\\wordpress-bundle/templates/generic.html.twig' )	...\NoticePlugin.php:37
Articles [Ajouter](http://wordpress-bundle/edition/wp-admin/post-new.php)

There is no controller defined : [Create one](http://wordpress-bundle/edition/wp-admin/edit.php?fix=controller)
Filtrer la liste des articles

    [Tous (1)](http://wordpress-bundle/edition/wp-admin/edit.php?post_type=post) | [Publié (1)](http://wordpress-bundle/edition/wp-admin/edit.php?post_status=publish&post_type=post) 

Rechercher des articles:
Sélectionnez l’action groupée
Filtrer par date
Filtrer par catégorie
1 élément

Liste des articles
Tout sélectionner
	
[Titre](http://wordpress-bundle/edition/wp-admin/edit.php?fix=controller&orderby=title&order=asc)
	Auteur/autrice	Catégories	Étiquettes	
[Commentaires](http://wordpress-bundle/edition/wp-admin/edit.php?fix=controller&orderby=comment_count&order=asc)
	
[Date](http://wordpress-bundle/edition/wp-admin/edit.php?fix=controller&orderby=date&order=desc)
Sélectionner [Bonjour tout le monde !](http://wordpress-bundle/edition/wp-admin/post.php?post=1&action=edit)
	
Bonjour tout le monde !
[Modifier](http://wordpress-bundle/edition/wp-admin/post.php?post=1&action=edit) |
| [Corbeille](http://wordpress-bundle/edition/wp-admin/post.php?post=1&action=trash&_wpnonce=9373b38de2) | [Voir](http://wordpress-bundle/bonjour-tout-le-monde)
	[wps_admin](http://wordpress-bundle/edition/wp-admin/edit.php?post_type=post&author=1)	[Non classé](http://wordpress-bundle/edition/wp-admin/edit.php?category_name=non-classe)	—Aucune étiquette	
[1(1 commentaire)](http://wordpress-bundle/edition/wp-admin/edit-comments.php?p=1&comment_status=approved)	
	Publié
21/02/2022 à 8h08	
Tout sélectionner
	
[Titre](http://wordpress-bundle/edition/wp-admin/edit.php?fix=controller&orderby=title&order=asc)
	Auteur/autrice	Catégories	Étiquettes	
[Commentaires](http://wordpress-bundle/edition/wp-admin/edit.php?fix=controller&orderby=comment_count&order=asc)
	
[Date](http://wordpress-bundle/edition/wp-admin/edit.php?fix=controller&orderby=date&order=desc)
Sélectionnez l’action groupée
1 élément'

**Comment by jerome-barbato** [comment]
Hello @celtic34fr thank you for your long report and your time, I have fixed numbers of bugs related to your issue.
It should work fine now. Could you confirm ?

**Comment by celtic34fr** [comment]
some problems : 
- first i execute : composer update, and wher it try to clear the cache : 
- `Executing script cache:clear [KO]
 [KO]
Script cache:clear returned with error code 1
!!
!!  In wp-db.php line 1753:
!!
!!    Warning: mysqli_real_connect(): (HY000/2002): Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée
!!
!!
!!
Script @auto-scripts was called via post-update-cmd`

and when i try tp get home page of website  : 
`
User Warning: $request must be renamed in "H:\wamp64\www\wordpress-bundle/public/index.php" : $httpRequest = Request::createFromGlobals();

    Exception Stack Trace 

ErrorException
in H:\wamp64\www\wordpress-bundle\vendor\metabolism\wordpress-bundle\src\WordpressBundle.php (line 110)

                return;
            global $request;
            if( is_object($request) && get_class($request) == 'Symfony\Component\HttpFoundation\Request' )
                trigger_error('$request must be renamed in "'.$this->public_dir.'/index.php" : $httpRequest = Request::createFromGlobals();', E_USER_WARNING);
            if (!defined('WP_DEBUG_LOG'))
                define('WP_DEBUG_LOG', realpath($this->log_dir . '/wp-errors.log'));
            $composer = $this->root_dir.'/composer.json';

`

I don't go futher, because i'm finishing the  website for my customer, and i don't have time to investigate on this errors.

----------------------------------------------------------------------------------------------------------------------------
quelques problèmes :
- d'abord j'exécute : composer update, et quand il essaie de vider le cache :
`Executing script cache:clear [KO]
 [KO]
Script cache:clear returned with error code 1
!!
!!  In wp-db.php line 1753:
!!
!!    Warning: mysqli_real_connect(): (HY000/2002): Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée
!!
!!
!!
Script @auto-scripts was called via post-update-cmd`

et quand j'essaie d'obtenir la page d'accueil du site Web:

`
User Warning: $request must be renamed in "H:\wamp64\www\wordpress-bundle/public/index.php" : $httpRequest = Request::createFromGlobals();

    Exception Stack Trace 

ErrorException
in H:\wamp64\www\wordpress-bundle\vendor\metabolism\wordpress-bundle\src\WordpressBundle.php (line 110)

                return;
            global $request;
            if( is_object($request) && get_class($request) == 'Symfony\Component\HttpFoundation\Request' )
                trigger_error('$request must be renamed in "'.$this->public_dir.'/index.php" : $httpRequest = Request::createFromGlobals();', E_USER_WARNING);
            if (!defined('WP_DEBUG_LOG'))
                define('WP_DEBUG_LOG', realpath($this->log_dir . '/wp-errors.log'));
            $composer = $this->root_dir.'/composer.json';

`
Je ne vais pas plus loin, car je suis en train de terminer le site Web de mon client et je n'ai pas le temps d'enquêter sur ces erreurs.

Gilbert ARMENGAUD
Celtic34fr
Béziers - Occitanie - France

**Comment by jerome-barbato** [comment]
Bonjour @celtic34fr avec la release de la 2.2, est ce que vous avez la possibilité de verifier que tout est ok maintenant ?
Merci d'avance !
