### ISSUE TITLE
Gestion de l'openGraph via YoastSEO (et hook template redirect en général)

### ISSUE THREAD

**Issue by undefinedfr** [wearemetabolism/wordpress-bundle#3]
Le hook '_template_redirect_' n'est pas appelé avant la création du context Twig, certaines données sont donc manquantes à Yoast pour générer les metas injectées dans le **wp_head**.

Pour corriger cela, il faudrait modifier **src/Traits/ContextTrait.php** pour ajouter le `do_action('template_redirect')` si ce n'est pas trop impactant pour la solution sinon appeler la fonction `wpseo_frontend_head_init()` si le module **wordpress-seo** (Yoast)  est présent.

_Solution de contournement, étendre du ContextTrait pour ajouter le do_action avant la création du context._

**Comment by wearemetabolism** [comment]
Solved in 1.1.0
