### ISSUE TITLE
Composer 2 support

### ISSUE THREAD

**Issue by bellu** [wearemetabolism/wordpress-bundle#31]
Hi,

i'm using Symfony 5.4 and i tried to install the package, but i got this error:

  Problem 1
    - metabolism/wordpress-bundle 2.0.2 requires metabolism/wordpress-core-installer ^1.0 -> satisfiable by metabolism/wordpress-core-installer[1.0.0, 1.1.0, 1.1.1].
    - metabolism/wordpress-bundle[2.0.0, ..., 2.0.1] require metabolism/wp-steroids 1.0.x-dev -> found metabolism/wp-steroids[1.0.x-dev] but it does not match your minimum-stability.
    - metabolism/wordpress-core-installer 1.0.0 requires composer-plugin-api ^1.0 -> found composer-plugin-api[2.3.0] but it does not match the constraint.
    - metabolism/wordpress-core-installer[1.1.0, ..., 1.1.1] require composer/installers ^1.0 -> found composer/installers[v1.0.0, ..., v1.12.0] but the package is fixed to v2.2.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - Root composer.json requires metabolism/wordpress-bundle ^2.0 -> satisfiable by metabolism/wordpress-bundle[2.0.0, 2.0.1, 2.0.2].

Switching to composer v1 solve the issue.
Is there a way to get this bundle work with composer v2?

**Comment by jerome-barbato** [comment]
Hi @bellu , something is strange, composer try to load the 2.0.1 that has a bug with the wp-steroids dependency, could you force the 2.0.2 in composer.json ?
