### ISSUE TITLE
Hooks and /edition/wp-login.php

### ISSUE THREAD

**Issue by Tim4c** [wearemetabolism/wordpress-bundle#34]
Hello @wearemetabolism ,

Can you tell me if this statement is correct ?
Wordpress Hooks are not fired on /edition/wp-login.php

Thanks in advance
Tim

**Comment by jerome-barbato** [comment]
Hello @Tim4c you are right, I have added the support of a LoginAction in the next release.
It will be available next week.

**Comment by Tim4c** [comment]
@wearemetabolism, thanks for your feedback! Do you have a roadmap of missing features to share?

**Comment by jerome-barbato** [comment]
Hello @Tim4c, I've just released the official 2.2.0 with login action support
I've started a new branch to add unit tests, not finished yet but helped me to fix some bugs.
I've no official roadmap, but I will now focus on stability, performance and also support for SF6.
If you have any requests, I would be happy to consider them.

**Comment by Tim4c** [comment]
Hello @jerome-barbato, Unfortunately, we have decided to stop using your project, and stick with the Wordpress standalone version... Thanks for your feedback, and good luck with the support of SF6.

**Comment by jerome-barbato** [comment]
Hello @Tim4c, thank you for your feedback !
May I know the reason ? This could guide me for the future versions.
Thank you

**Comment by Tim4c** [comment]
Hey @jerome-barbato, Just bad timing for us ;)
