### ISSUE TITLE
flush_rewrite_rules() is called on every page load

### ISSUE THREAD

**Issue by markeasting** [wearemetabolism/wordpress-bundle#36]
Hi there,

It seems like `flush_rewrite_rules()` is called on each page load here:

https://github.com/jerome-barbato/wordpress-bundle/blob/fae875be096443103edfab77e4f033ff8de969e6/config/routing.php#L191-L195

I believe wordpress clears the rewrites in the options table and then fills it with new values - it seems inefficient to do this on every page load :)

Maybe the code could be wrapped in `APP_ENV` / `WP_ENV` check, such that the flush only happens on a development environment.

**Comment by jerome-barbato** [comment]
Hello @markeasting routing.php is cached by Symfony, it's used to generate cache/url_generating_routes.php and cache/url_matching_routes.php but only once, or if the file changed.
You can try to add an echo "debug"; after  flush_rewrite_rules(); you will see it called only once.
