### ISSUE TITLE
Redirect `wp-admin` to Wordpress admin

### ISSUE THREAD

**Issue by markeasting** [wearemetabolism/wordpress-bundle#39]
In `Metabolism\WordpressBundle\Action\FrontAction`, if the user visits `/edition` (or in our case, `/cms`), the page is nicely redirected to the Wordpress admin interface.

It would be nice if this could also redirect the page if a user visits `/wp-admin` (and maybe also sub-pages, like `/wp-admin/upload.php`), since most clients are used to visit this url when trying to access the Wordpress interface.

**Comment by jerome-barbato** [comment]
Hello @markeasting in fact I made it by design, the reason is to prevent robots and hackers to detect easily Wordpress in the subfolder.

If you still want this redirection I may suggest you to override the redirect frontAction

**Comment by markeasting** [comment]
Hi Jerome,

No problem, and you have a good point there. We'll consider it and add it to our own FrontAction if needed.
