### ISSUE TITLE
Add support for `DISALLOW_FILE_MODS` to prevent plugin updates

### ISSUE THREAD

**Issue by markeasting** [wearemetabolism/wordpress-bundle#40]
Hi Jerome,

Since we are using CI/CD to update our wp core and plugins (via composer), our users shouldn't be able to edit or install plugins. It seems possible to disable plugin installs via the `DISALLOW_FILE_MODS` constant. 

Could you add support for this constant in `Metabolism\WordpressBundle\Loader\ConfigLoader`?  Maybe it could also be integrated with the .env file or via the WP Steroids plugin?

**Comment by jerome-barbato** [comment]
Hi @markeasting , now released in latest version https://github.com/jerome-barbato/wordpress-bundle/blob/f835d7579f7cc1a7d4873d0fe71377da8b6c8c81/src/Loader/ConfigLoader.php#L196
Thank you !
