### ISSUE TITLE
Add support for WP_ENVIRONMENT_TYPE

### ISSUE THREAD

**Issue by markeasting** [wearemetabolism/wordpress-bundle#41]
Hi Jerome,

Wordpress supports an 'env' setting via the `WP_ENVIRONMENT_TYPE` constant. Some plugins use this to change their behaviour on development sites. See https://developer.wordpress.org/reference/functions/wp_get_environment_type

Suggested addition: 

```diff
// src/Loader/ConfigLoader.php

$env = env('APP_ENV') ?: (env('WP_ENV') ?: 'dev');

/**
 * Define basic environment
 */
+ define('WP_ENVIRONMENT_TYPE', $env === 'dev' ? 'development' : 'production');
define('WP_ENV', $env);
define('WP_DEBUG', $env === 'dev');
define('WP_DEBUG_DISPLAY', WP_DEBUG);
define('SCRIPT_DEBUG', WP_DEBUG);
```

Related to #40

**Comment by jerome-barbato** [comment]
Hello, @markeasting! You are absolutely right. I apologize for the delayed response, as I am currently on vacation. I will review all your comments by the end of next week. Thank you for your valuable contributions!

**Comment by jerome-barbato** [comment]
Released in latest version https://github.com/jerome-barbato/wordpress-bundle/blob/f835d7579f7cc1a7d4873d0fe71377da8b6c8c81/src/Loader/ConfigLoader.php#L56
