### ISSUE TITLE
License question and issue

### ISSUE THREAD

**Issue by Blackbam** [wearemetabolism/wordpress-bundle#42]
The README.md says this is GPL 3.0 but the license file says this is AGPL. Why do you put that extremely restrictive license on a combination of Symfony - which is gratefully MIT licensed - and WordPress - which is GPLv2.0 licensed? 

This makes a project which is essentially a great idea totally useless for any closed source project, even if it is a server-side application which also means growing the project and contribution is much less likely.

In doubt I must assume that the license is AGPL just as in the license file.

More information: https://softwareengineering.stackexchange.com/questions/107883/agpl-what-you-can-do-and-what-you-cant

**Comment by markeasting** [comment]
Same issue here!

**Comment by jerome-barbato** [comment]
Hi guys, you are absolutely right ! I changed it to MIT !
